### ISSUE TITLE
Move to Org (RxSwiftCommunity)

### ISSUE THREAD

**Issue by esttorhe** [RxSwiftCommunity/RxViewModel#10]
# [`RxSwiftCommunity`](https://github.com/RxSwiftCommunity)

Prep:
- [x] Update podspecs with new remote URL (560fda84c1214ba1d0238cf35154833152d6d610)
- [x] Update CI badge (560fda84c1214ba1d0238cf35154833152d6d610)
- ~~Update CI settings~~ See #12
- [x] Fork the repo back to my personal account (I really don't feel like sending a `PR` to fix `CocoaPods` trunk, forking is so much easier
  + This means the pod will still be maintained by me (in theory by anyone but for now i'll be pushing to trunk)

**Comment by ashfurrow** [comment]
This all makes sense – the pod can be maintained by you, but it should probably point to the new URL instead of your fork. This is what I did for NSObject+Rx. 

Looks good! Once you transfer ownership, one of the admins can accept it. Probably easiest to grab one of us from Slack and coordinate. 

![](http://media.giphy.com/media/V2xbsCrxcLQSQ/giphy.gif)

**Comment by kzaher** [comment]
@esttorhe I've gave you admin access :)

**Comment by esttorhe** [comment]
Thanks @kzaher 

@ashfurrow i'll ping you or someone on one of the Slacks i have some of you :smile: 
At this rate I think I'll end up adding another Slack team :scream:

**Comment by esttorhe** [comment]
I can't add `RxSwiftCommunity` to `CircleCI`.

Currently this repo is being tested there (I assume because my account somehow let it run after transitioning ownership) but don't know for how long it will keep working like this.

**Comment by ashfurrow** [comment]
Looks like it's because CircleCI hasn't enabled iOS support for the org yet – I had this problem when I moved over Moya. I'll contact them to get them to switch it (they like me).

**Comment by esttorhe** [comment]
Got it :ok_hand: 

I'll probably close this issue and will open a new one to follow on the CI transition

**Comment by ashfurrow** [comment]
Hmm. Just saw this in my inbox (posted 23 hours ago):

> Our iOS support has been free for about a year while we’ve been building core product features. We appreciate your support as a beta user!
> 
> I'm writing to let you know that the free beta program is ending this month. To remain building iOS projects, you will need to take action before the end of November. 
> 
> We will be reaching out to to the main contacts for your org within the next 2 days outlining subscription options - please feel free to reach out if you are looking to upgrade and have not received an email by then.
> 
> As a thank-you for being a beta customer, you have reserved access to this new, limited release. We’re quickly adding much more to our iOS offering (more capacity, faster VM updates, and engineering support) as we prepare for wider, general release. 

So I don't know if they'll grant access to a program that's ending this month. It's worth while considering moving to Travis or somewhere else.

**Comment by esttorhe** [comment]
Mmm; weird; don't have anything resembling that email on my inbox.

Oh well, if they are not offering a free tier for OSS projects I guess I'll just move it to `TravisCI` then (or something else if someone has any ideas)

**Comment by ashfurrow** [comment]
It's not an email, it's their in-browser support. You open it by clicking the "Support" icon on the left I think. 

See the thing is they're not saying that it won't be free, it's super-confusing.

**Comment by esttorhe** [comment]
Argh…
Asked Marc O'Morain on Twitter; he's a developer at `CircleCI`, perhaps he'll be able to clarify this for us.

**Comment by esttorhe** [comment]
@ashfurrow I created #12 to «track» this
