### ISSUE TITLE
Update CI Settings

### ISSUE THREAD

**Issue by esttorhe** [RxSwiftCommunity/RxViewModel#12]
From #10 

Either fix the settings on `CircleCI` or transition to `TravisCI` if `CircleCI` is no longer an option.

**Comment by esttorhe** [comment]
@ashfurrow I found this on their website; under «pricing plan» for this org.

>Builds will run in a single container.
>
>1 container is free, forever.
>
>Additionally, projects that are public on GitHub will build with 3 extra containers -- our gift to free and open source software

**Comment by ashfurrow** [comment]
Super! That's a relief :sweat_smile:

**Comment by esttorhe** [comment]
<blockquote class="twitter-tweet" lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/esttorhe">@esttorhe</a> that&#39;s enabled now (go chat-ops!) I can totally admin circle on my phone! We have a per org setting that I just enabled.</p>&mdash; Marc O&#39;Morain (@atmarc) <a href="https://twitter.com/atmarc/status/667165178723753988">November 19, 2015</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by esttorhe** [comment]
This is fixed now; closing it.
