### ISSUE TITLE
Update to rxswift & rxcocoa 2.2?

### ISSUE THREAD

**Issue by gloryluu** [RxSwiftCommunity/RxViewModel#23]
I think you should you bump a newer version in podspec?

**Comment by esttorhe** [comment]
Defo. 

Sadly (for my `OSS` contributions) I've been super busy with work lately and haven't had the time to update it.

Will try to do so this weekend.

`PR`s are welcomed though :stuck_out_tongue_winking_eye:

**Comment by esttorhe** [comment]
`PR` #27 bumped to `2.4.0`
