### ISSUE TITLE
RxViewModel is depending on an old version of RxCocoa

### ISSUE THREAD

**Issue by eliasbagley** [RxSwiftCommunity/RxViewModel#29]
I got this error today when trying to `pod install` RxViewModel with RxCoreData - 

[!] Unable to satisfy the following requirements:

- `RxCocoa (~> 1.8)` required by `RxViewModel (0.2.1)`
- `RxCocoa (~> 2.5)` required by `RxCoreData (0.1.0)`

**Comment by esttorhe** [comment]
Hi there @eliasbagley sorry i have not responded earlier but I've been away in a trip.

I'll check this week and will try to fix it.

For now I think pointing `RxViewModel` to `master` on your `Podfile` should give you a compiling version.
Need to double check what's going on with the `podspec`

**Comment by esttorhe** [comment]
Hi there @eliasbagley version `3.1.2` is out which uses `RxSwift` `2.4`

Will release a new version pointing to `2.5` in the following hours though :)

**Comment by esttorhe** [comment]
@eliasbagley `RxViewModel` now uses `RxSwift` `2.5` as seen here https://github.com/RxSwiftCommunity/RxViewModel/releases/tag/3.1.3

I'm closing this issue now.

Feel free to open another one if you think is needed 😄
