### ISSUE TITLE
Retain cycle

### ISSUE THREAD

**Issue by sprynmr** [RxSwiftCommunity/RxViewModel#31]
When subclassing RxViewModel, I'm seeing a retain cycle with a lazy property observable chain that starts with `didBecomeActive`. I found what I thought was the issue and submitted PR https://github.com/RxSwiftCommunity/RxViewModel/pull/30, but I'm still seeing it.

```
    lazy var slotDriver: Driver<[PromotionsPage.Slot]> = {
        return self.didBecomeActive
            .mapReplace([])
            .asDriver(onErrorJustReturn: [])
    }()
```

**Comment by esttorhe** [comment]
Fixed with #30
