### ISSUE TITLE
Update Swift 3

### ISSUE THREAD

**Issue by gorbat-o** [RxSwiftCommunity/RxViewModel#44]
Hey,

Maybe an update for swift 3 ? =D

Thanks

**Comment by esttorhe** [comment]
Hi @gorbat-o I'm in the middle of relocating to 🇩🇪 and haven't had much time to work on my OSS projects (also I don't currently have internet at the apartment).

I think Greg already started tackling this with #43.

If you could test that the branch works and behaves as expected and can vouch for the fix I can totally merge that and release the `Swift 3` support. 😄

**Comment by nechris** [comment]
Seemingly `var disposeKey: Bag<Disposable>.KeyType?` doesn't work anymore as `Bag` and `KeyType` seem to be private now. When explicitly setting the `Bag` struct and `KeyType` type alias in RxSwift to public, it works.
Any thoughts on this?

**Comment by YMonnier** [comment]
Soon Swift 4?

**Comment by freak4pc** [comment]
Doesn't seem like this project is maintained anymore :(

**Comment by esttorhe** [comment]
Apologies to all @nechris, @YMonnier and @freak4pc 

Currently, I don't have much time to put into `OSS` (sadly) and haven't had the time to keep maintaining this.

I've tried to hand it over to the community seeing that it has been used by a couple more than just me and some friends (which is awesome), but haven't been lucky yet.

If someone sends a `PR` with support for 3 and/or 4 I would love to merge; also everyone who gets a merged `PR` is invited to be part of `RxSwiftCommunity` and can help maintain this and other projects (if the person wishes to)

Besides this I can't guarantee when I will have time to update this; suffice it to say that if I can squeeze some time for `OSS` the first project I will tackle will this

**Comment by freak4pc** [comment]
Just pushed a PR for Swift 3 & 4. Let me know if any questions arise :) 
https://github.com/RxSwiftCommunity/RxViewModel/pull/45
