### ISSUE TITLE
You should make RxViewModel class "open"

### ISSUE THREAD

**Issue by lovesuper** [RxSwiftCommunity/RxViewModel#50]
I have ```Cannot inherit from non-open class 'RxViewModel' outside of its defining module``` all around my project because of you annotate rxviewmodel class with "public" annotation instead of "open"

**Comment by esttorhe** [comment]
You are 💯  correct @lovesuper.

I just replaced the one `public` usage for `open` to make the class subclassable.

Once `CI` is 💚  I'll merge and release a new version.

**Comment by esttorhe** [comment]
This should be fixed now; i'll release a new version in the next hour

**Comment by esttorhe** [comment]
🚫  done
