### ISSUE TITLE
Can't use RxSwift 3.6.1

### ISSUE THREAD

**Issue by AYastrebov** [RxSwiftCommunity/RxViewModel#54]
Can't use latest RxSwift, when installing with cocoapods. Only version 3.5.0 is supported now

```Installing RxSwift 3.5.0 (was 3.6.1)```

**Comment by freak4pc** [comment]
Hey @AYastrebov 
I have a PR out to fix this. Any way you can point your Podfile to the Podspec of the specific branch to see if it resolves it? Thanks !

**Comment by AYastrebov** [comment]
Thanks, @freak4pc 
```pod 'RxViewModel', :git => 'https://github.com/RxSwiftCommunity/RxViewModel.git', :branch => 'fix/loosen-hard-dependency'``` fixed this issue

**Comment by freak4pc** [comment]
Cool. I'll merge this but will still have to wait for @esttorhe to publish a new Spec along with the RxViewModel 5.0.0 release

**Comment by freak4pc** [comment]
Fixed via #55
